# Generated by Django 2.0.4 on 2018-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(choices=[('SUN', 'sunday'), ('MON', 'monday'), ('TUE', 'tuesday'), ('WED', 'wednssday'), ('THU', 'thursday')], max_length=3),
        ),
    ]
