# Generated by Django 2.0.4 on 2018-07-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180708_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='day',
        ),
    ]
