# Generated by Django 2.0.4 on 2018-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
