# Generated by Django 2.0.4 on 2018-07-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20180708_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='write something about yourself ...', max_length=500),
        ),
    ]
