# Generated by Django 2.0.4 on 2018-07-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('year', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Seconde'), (3, 'Third'), (4, 'Fourth')], null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
